### ISSUE TITLE
居然没有“捂脸”🤦?

### ISSUE THREAD

**Issue by alick** [levinit/fcitx-emoji#1]
建议添加：

```
wulian 🤦
facepalm 🤦
```

参考文献：

[1] https://emojipedia.org/face-palm/
[2] https://m.7230.com/a51983

**Comment by levinit** [comment]
马上添加😂 我在乎的是居然找不到滑稽 🙃:smirk:

**Comment by alick** [comment]
你说的滑稽最接近的可能是 😏 https://emojipedia.org/smirking-face/

Regards,

**Comment by levinit** [comment]
这个知道 先凑合用 不过还是没滑稽喜感(手动滑稽)
